[2023-06-23T05:37:32.432+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:36:55.263823+00:00 [queued]>
[2023-06-23T05:37:32.439+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:36:55.263823+00:00 [queued]>
[2023-06-23T05:37:32.439+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:37:32.439+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-06-23T05:37:32.439+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:37:32.450+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): hello_task> on 2023-06-23 05:36:55.263823+00:00
[2023-06-23T05:37:32.452+0000] {standard_task_runner.py:55} INFO - Started process 106 to run task
[2023-06-23T05:37:32.454+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_task', 'manual__2023-06-23T05:36:55.263823+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp9cxjq8ra']
[2023-06-23T05:37:32.455+0000] {standard_task_runner.py:83} INFO - Job 213: Subtask hello_task
[2023-06-23T05:37:33.062+0000] {task_command.py:389} INFO - Running <TaskInstance: hello_world.hello_task manual__2023-06-23T05:36:55.263823+00:00 [running]> on host hello-world-hello-task-8690023c648440fba0b28e8bd0c929d2
[2023-06-23T05:37:34.016+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:58 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:37:34.018+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:64 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:37:34.018+0000] {pod_generator.py:424} WARNING - Model file /opt/***/pod_templates/pod_template.yaml does not exist
[2023-06-23T05:37:34.062+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T05:36:55.263823+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-23T05:36:55.263823+00:00
[2023-06-23T05:37:34.062+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 11, in print_hello
    file_path = context["dag_run"].conf["file_path"]
KeyError: 'file_path'
[2023-06-23T05:37:34.074+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=hello_world, task_id=hello_task, execution_date=20230623T053655, start_date=20230623T053732, end_date=20230623T053734
[2023-06-23T05:37:34.088+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 213 for task hello_task ('file_path'; 106)
[2023-06-23T05:37:34.121+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T05:37:34.149+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
