[2023-06-23T05:23:06.190+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:22:27.429964+00:00 [queued]>
[2023-06-23T05:23:06.197+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:22:27.429964+00:00 [queued]>
[2023-06-23T05:23:06.197+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:23:06.197+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T05:23:06.198+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:23:06.209+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): hello_task> on 2023-06-23 05:22:27.429964+00:00
[2023-06-23T05:23:06.211+0000] {standard_task_runner.py:55} INFO - Started process 106 to run task
[2023-06-23T05:23:06.213+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_task', 'manual__2023-06-23T05:22:27.429964+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpxw43k45v']
[2023-06-23T05:23:06.214+0000] {standard_task_runner.py:83} INFO - Job 211: Subtask hello_task
[2023-06-23T05:23:06.963+0000] {task_command.py:389} INFO - Running <TaskInstance: hello_world.hello_task manual__2023-06-23T05:22:27.429964+00:00 [running]> on host hello-world-hello-task-8df944bc643c4ae3bca53170c4d914c4
[2023-06-23T05:23:07.719+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:58 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:23:07.721+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:64 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:23:07.722+0000] {pod_generator.py:424} WARNING - Model file /opt/***/pod_templates/pod_template.yaml does not exist
[2023-06-23T05:23:07.767+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T05:22:27.429964+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-23T05:22:27.429964+00:00
[2023-06-23T05:23:07.769+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 11, in print_hello
    with open("/data/hello_world.txt", "w") as f:
PermissionError: [Errno 13] Permission denied: '/data/hello_world.txt'
[2023-06-23T05:23:07.778+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_task, execution_date=20230623T052227, start_date=20230623T052306, end_date=20230623T052307
[2023-06-23T05:23:07.786+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 211 for task hello_task ([Errno 13] Permission denied: '/data/hello_world.txt'; 106)
[2023-06-23T05:23:07.828+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T05:23:07.850+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
