[2023-06-23T05:25:04.217+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:24:26.850129+00:00 [queued]>
[2023-06-23T05:25:04.224+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_task manual__2023-06-23T05:24:26.850129+00:00 [queued]>
[2023-06-23T05:25:04.224+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:25:04.224+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-23T05:25:04.224+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-23T05:25:04.236+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): hello_task> on 2023-06-23 05:24:26.850129+00:00
[2023-06-23T05:25:04.239+0000] {standard_task_runner.py:55} INFO - Started process 106 to run task
[2023-06-23T05:25:04.242+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_task', 'manual__2023-06-23T05:24:26.850129+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpjjdzdhtj']
[2023-06-23T05:25:04.243+0000] {standard_task_runner.py:83} INFO - Job 212: Subtask hello_task
[2023-06-23T05:25:04.762+0000] {task_command.py:389} INFO - Running <TaskInstance: hello_world.hello_task manual__2023-06-23T05:24:26.850129+00:00 [running]> on host hello-world-hello-task-b9b7a8457ce54431828218303e6e3523
[2023-06-23T05:25:05.584+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:58 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:25:05.585+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.8/site-packages/***/kubernetes/kube_config.py:64 DeprecationWarning: The namespace option in [kubernetes] has been moved to the namespace option in [kubernetes_executor] - the old setting has been used, but please update your config.
[2023-06-23T05:25:05.587+0000] {pod_generator.py:424} WARNING - Model file /opt/***/pod_templates/pod_template.yaml does not exist
[2023-06-23T05:25:05.638+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hello_world
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-23T05:24:26.850129+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-23T05:24:26.850129+00:00
[2023-06-23T05:25:05.640+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 11, in print_hello
    with open("/data/hello_world.txt", "w") as f:
PermissionError: [Errno 13] Permission denied: '/data/hello_world.txt'
[2023-06-23T05:25:05.651+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_task, execution_date=20230623T052426, start_date=20230623T052504, end_date=20230623T052505
[2023-06-23T05:25:05.662+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 212 for task hello_task ([Errno 13] Permission denied: '/data/hello_world.txt'; 106)
[2023-06-23T05:25:05.696+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-23T05:25:05.725+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
